"""The per-user delivery settings row (D-33, D-34). Repo: pure DB I/O, no commits, no business
rules."""

from datetime import UTC, datetime
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.ext.asyncio import AsyncSession

from upmovies.app.models import UserSettings


async def get(db: AsyncSession, *, user_id: UUID) -> UserSettings | None:
    return await db.get(UserSettings, user_id)


async def create_if_absent(db: AsyncSession, *, user_id: UUID, ical_token: str) -> UserSettings:
    """Insert this user's row unless it is already there, and return whichever row now exists.

    `ON CONFLICT DO NOTHING` rather than a read-then-insert, because the read *is* what creates
    the row here (D-31's settings are lazily made on first GET) and the settings screen's first
    paint is exactly the moment two requests arrive together — one from the page, one from the
    calendar panel beside it. A plain insert would make the loser of that race a 500 on a read;
    this makes it a second reader of the same row, with the same token. The `ical_token`
    generated by the loser is simply not used: a token that never reached a URL costs nothing,
    and the alternative — returning it anyway — would hand two callers different tokens for one
    row."""
    await db.execute(
        pg_insert(UserSettings)
        .values(user_id=user_id, ical_token=ical_token)
        .on_conflict_do_nothing(index_elements=["user_id"])
    )
    row = await db.scalar(
        select(UserSettings)
        .where(UserSettings.user_id == user_id)
        .execution_options(populate_existing=True)
    )
    assert row is not None  # the insert above either wrote it or found it already written
    return row


async def set_digest_cadence(db: AsyncSession, row: UserSettings, *, digest_cadence: str) -> None:
    """Replace the cadence on the loaded model. Caller commits."""
    row.digest_cadence = digest_cadence
    row.updated_at = datetime.now(UTC)


async def set_ical_token(db: AsyncSession, row: UserSettings, *, ical_token: str) -> None:
    """Replace the calendar token on the loaded model. Caller commits."""
    row.ical_token = ical_token
    row.updated_at = datetime.now(UTC)
