"""'add uq_event_catalog_change'

Revision ID: 1624d2f7f412
Revises: 49ffb208d5da
Create Date: 2026-08-11 00:53:01.952320+00:00

"""
from alembic import op
import sqlalchemy as sa


revision = '1624d2f7f412'
down_revision = '49ffb208d5da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_event_catalog_change', 'event', ['film_id', 'event_type', 'occurred_at'], unique=True, schema='news', postgresql_where=sa.text("provenance = 'catalog'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_event_catalog_change', table_name='event', schema='news', postgresql_where=sa.text("provenance = 'catalog'"))
    # ### end Alembic commands ###
