"""'add event.subject_key'

Revision ID: 1b46a53537db
Revises: 580e5e0d3714
Create Date: 2026-07-04 16:43:53.226916+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '1b46a53537db'
down_revision = '580e5e0d3714'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('subject_key', postgresql.ARRAY(sa.Text()), nullable=True), schema='news')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'subject_key', schema='news')
    # ### end Alembic commands ###
