"""'add film_company_change and company event types (NEU-1433)'

Revision ID: 1cdd4fe77a5e
Revises: a5e1c93b7d40
Create Date: 2026-09-21 21:18:31.606018+00:00

"""
from alembic import op
import sqlalchemy as sa

from upmovies.catalog.models import INSTALL_FILM_FIELD_CHANGE_TRIGGER


revision = '1cdd4fe77a5e'
down_revision = 'a5e1c93b7d40'
branch_labels = None
depends_on = None

_NEW_EVENT_TYPES = (
    "'announced', 'casting', 'company_attached', 'company_removed', 'credit_removed', "
    "'crew_attached', 'now_available', 'production_start', 'production_wrap', "
    "'release_date', 'trailer', 'first_look', 'other'"
)
_OLD_EVENT_TYPES = (
    "'announced', 'casting', 'credit_removed', 'crew_attached', 'now_available', "
    "'production_start', 'production_wrap', 'release_date', 'trailer', 'first_look', 'other'"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film_company_change',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('film_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('change', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('carded_by_event_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['carded_by_event_id'], ['news.event.id'], name='fk_film_company_change_carded_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['catalog.production_company.id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['catalog.film.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_index('ix_catalog_film_company_change_carded_by', 'film_company_change', ['carded_by_event_id'], unique=False, schema='catalog')
    op.create_index('ix_catalog_film_company_change_lookup', 'film_company_change', ['film_id', 'changed_at'], unique=False, schema='catalog')
    op.add_column('film', sa.Column('companies_observed_at', sa.DateTime(timezone=True), nullable=True), schema='catalog')
    # ### end Alembic commands ###

    # `companies_observed_at` joins FILM_FIELD_CHANGE_DENYLIST, so the trigger function has to
    # be replaced to pick it up — as `credits_observed_at` did in 957421e2651e and
    # `tmdb_missing_at` in 8a3a615c3c8d. It has to happen **before** the backfill below, which
    # updates every film row: without it that one statement writes a `film_field_change` row
    # per film, which `field_events` would card as a public event about our own bookkeeping and
    # which would make the entire catalog look active to `dormant_film_clause` on the same day.
    # CREATE OR REPLACE, so reinstalling is idempotent; one op.execute per statement because
    # asyncpg's extended query protocol rejects multi-statement calls (see the note in
    # models.py).
    for stmt in INSTALL_FILM_FIELD_CHANGE_TRIGGER:
        op.execute(stmt)

    # Every existing film is stamped as already observed, which is the opposite of what the
    # credit and release-date markers did on their own migrations — and it is deliberate
    # (D-1436.3, posted on NEU-1433 2026-09-21).
    #
    # The marker is the whole of "first observation is a baseline, never a change" for
    # companies, and NEU-1436 keys the EF-4 admission exception on it being NULL. Left NULL
    # here, every film already in the catalog would read as a first observation on its next
    # refresh: today that is a silent baseline, but the moment NEU-1436 ships it becomes a
    # `company_attached` card for every followed studio on every film in the catalog, all in
    # one pass. Stamping now makes the first diff after this deploy a real diff.
    #
    # `now()` rather than the film's `created_at`: the claim the column makes is "the catalog
    # holds an observation of this film's companies", and what makes that true is this
    # migration, not the day the film was admitted.
    op.execute("UPDATE catalog.film SET companies_observed_at = now()")

    # The two new types, registered in the one place a value outside the vocabulary is refused.
    op.execute("ALTER TABLE news.event DROP CONSTRAINT ck_event_type")
    op.execute(
        f"ALTER TABLE news.event ADD CONSTRAINT ck_event_type CHECK (event_type IN ({_NEW_EVENT_TYPES}))"
    )


def downgrade() -> None:
    # A company card cannot satisfy the old constraint, so the events the phase carded go with
    # the type — there is nothing else they could be. Their summaries follow on the
    # `event_summary` FK cascade, and `film_company_change.carded_by_event_id` is SET NULL, so
    # the history rows survive and would be re-carded if the type ever came back.
    op.execute("DELETE FROM news.event WHERE event_type IN ('company_attached', 'company_removed')")
    op.execute("ALTER TABLE news.event DROP CONSTRAINT ck_event_type")
    op.execute(
        f"ALTER TABLE news.event ADD CONSTRAINT ck_event_type CHECK (event_type IN ({_OLD_EVENT_TYPES}))"
    )

    # The trigger function is deliberately left as installed above, matching 8a3a615c3c8d: its
    # denylist entry for a column that no longer exists is inert, and rebuilding the previous
    # function body here would fork the one place that SQL is written.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('film', 'companies_observed_at', schema='catalog')
    op.drop_index('ix_catalog_film_company_change_lookup', table_name='film_company_change', schema='catalog')
    op.drop_index('ix_catalog_film_company_change_carded_by', table_name='film_company_change', schema='catalog')
    op.drop_table('film_company_change', schema='catalog')
    # ### end Alembic commands ###
