"""catalog.film_field_change.carded_by_event_id (NEU-1446)

D-1446.2. The franchise half of D-5's stamp. `film_credit_change` and `film_company_change`
each carry a `carded_by_event_id` recording which event published which change; the collection
half had nowhere to record it, because a film joining a franchise is a `catalog.film` column
change and lands in `film_field_change` rather than in a table of its own.

One stamp shape for all three kinds, rather than a time-based carve-out for collections — which
would diverge from the other two and would attribute an unrelated later re-file to the card that
broke the first one.

**No backfill.** No story card has ever carded a collection change: until this ticket nothing
resolved an organisation mention to a `catalog.collection` row at all, so every existing row is
correctly NULL.

Only the `collection_id` rows will ever carry it. The `status` rows this table also holds are
suppressed by `sweep.field_events._already_carded` ("does this film already have one of these
cards"), which no story card can satisfy — the status vocabulary is not the story vocabulary.

Autogenerated and kept as generated: a nullable column, its index and its FK are exactly what
the model declares, and the parity test compares the constraint *names*, which is why
`fk_film_field_change_carded_by` is spelled here and on the model.

Revision ID: 228c542216fa
Revises: ee38f2c9eb2f
Create Date: 2026-09-23 02:37:16.578029+00:00

"""

import sqlalchemy as sa
from alembic import op

revision = "228c542216fa"
down_revision = "ee38f2c9eb2f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "film_field_change",
        sa.Column("carded_by_event_id", sa.UUID(), nullable=True),
        schema="catalog",
    )
    op.create_index(
        "ix_film_field_change_carded_by",
        "film_field_change",
        ["carded_by_event_id"],
        unique=False,
        schema="catalog",
    )
    op.create_foreign_key(
        "fk_film_field_change_carded_by",
        "film_field_change",
        "event",
        ["carded_by_event_id"],
        ["id"],
        source_schema="catalog",
        referent_schema="news",
        ondelete="SET NULL",
    )


def downgrade() -> None:
    op.drop_constraint(
        "fk_film_field_change_carded_by",
        "film_field_change",
        schema="catalog",
        type_="foreignkey",
    )
    op.drop_index(
        "ix_film_field_change_carded_by", table_name="film_field_change", schema="catalog"
    )
    op.drop_column("film_field_change", "carded_by_event_id", schema="catalog")
