"""'full tmdb capture and normalized catalog tables'

Revision ID: 26f140c4f334
Revises: 3f83224e776f
Create Date: 2026-06-19 22:34:55.647552+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '26f140c4f334'
down_revision = '3f83224e776f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('poster_path', sa.Text(), nullable=True),
    sa.Column('backdrop_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_table('genre',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_table('production_company',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('logo_path', sa.Text(), nullable=True),
    sa.Column('origin_country', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_table('production_country',
    sa.Column('iso_3166_1', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('iso_3166_1'),
    schema='catalog'
    )
    op.create_table('spoken_language',
    sa.Column('iso_639_1', sa.Text(), nullable=False),
    sa.Column('english_name', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('iso_639_1'),
    schema='catalog'
    )
    op.create_table('film_genre',
    sa.Column('film_id', sa.UUID(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['catalog.film.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['catalog.genre.id'], ),
    sa.PrimaryKeyConstraint('film_id', 'genre_id'),
    schema='catalog'
    )
    op.create_table('film_production_company',
    sa.Column('film_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['catalog.production_company.id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['catalog.film.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('film_id', 'company_id'),
    schema='catalog'
    )
    op.create_table('film_production_country',
    sa.Column('film_id', sa.UUID(), nullable=False),
    sa.Column('iso_3166_1', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['catalog.film.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['iso_3166_1'], ['catalog.production_country.iso_3166_1'], ),
    sa.PrimaryKeyConstraint('film_id', 'iso_3166_1'),
    schema='catalog'
    )
    op.create_table('film_spoken_language',
    sa.Column('film_id', sa.UUID(), nullable=False),
    sa.Column('iso_639_1', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['catalog.film.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['iso_639_1'], ['catalog.spoken_language.iso_639_1'], ),
    sa.PrimaryKeyConstraint('film_id', 'iso_639_1'),
    schema='catalog'
    )
    op.add_column('film', sa.Column('adult', sa.Boolean(), nullable=True), schema='catalog')
    op.add_column('film', sa.Column('backdrop_path', sa.Text(), nullable=True), schema='catalog')
    op.add_column('film', sa.Column('budget', sa.BigInteger(), nullable=True), schema='catalog')
    op.add_column('film', sa.Column('homepage', sa.Text(), nullable=True), schema='catalog')
    op.add_column('film', sa.Column('original_language', sa.Text(), nullable=True), schema='catalog')
    op.add_column('film', sa.Column('popularity', sa.Float(), nullable=True), schema='catalog')
    op.add_column('film', sa.Column('revenue', sa.BigInteger(), nullable=True), schema='catalog')
    op.add_column('film', sa.Column('runtime', sa.Integer(), nullable=True), schema='catalog')
    op.add_column('film', sa.Column('tagline', sa.Text(), nullable=True), schema='catalog')
    op.add_column('film', sa.Column('video', sa.Boolean(), nullable=True), schema='catalog')
    op.add_column('film', sa.Column('vote_average', sa.Float(), nullable=True), schema='catalog')
    op.add_column('film', sa.Column('vote_count', sa.Integer(), nullable=True), schema='catalog')
    op.add_column('film', sa.Column('origin_country', postgresql.ARRAY(sa.Text()), nullable=True), schema='catalog')
    op.add_column('film', sa.Column('collection_id', sa.Integer(), nullable=True), schema='catalog')
    op.add_column('film', sa.Column('tmdb_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='catalog')
    op.create_foreign_key(None, 'film', 'collection', ['collection_id'], ['id'], source_schema='catalog', referent_schema='catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'film', schema='catalog', type_='foreignkey')
    op.drop_column('film', 'tmdb_raw', schema='catalog')
    op.drop_column('film', 'collection_id', schema='catalog')
    op.drop_column('film', 'origin_country', schema='catalog')
    op.drop_column('film', 'vote_count', schema='catalog')
    op.drop_column('film', 'vote_average', schema='catalog')
    op.drop_column('film', 'video', schema='catalog')
    op.drop_column('film', 'tagline', schema='catalog')
    op.drop_column('film', 'runtime', schema='catalog')
    op.drop_column('film', 'revenue', schema='catalog')
    op.drop_column('film', 'popularity', schema='catalog')
    op.drop_column('film', 'original_language', schema='catalog')
    op.drop_column('film', 'homepage', schema='catalog')
    op.drop_column('film', 'budget', schema='catalog')
    op.drop_column('film', 'backdrop_path', schema='catalog')
    op.drop_column('film', 'adult', schema='catalog')
    op.drop_table('film_spoken_language', schema='catalog')
    op.drop_table('film_production_country', schema='catalog')
    op.drop_table('film_production_company', schema='catalog')
    op.drop_table('film_genre', schema='catalog')
    op.drop_table('spoken_language', schema='catalog')
    op.drop_table('production_country', schema='catalog')
    op.drop_table('production_company', schema='catalog')
    op.drop_table('genre', schema='catalog')
    op.drop_table('collection', schema='catalog')
    # ### end Alembic commands ###
