"""'add email_token new_email'

Revision ID: 3e6c7bb5536e
Revises: c206c3092a40
Create Date: 2026-09-16 19:40:33.591698+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '3e6c7bb5536e'
down_revision = 'c206c3092a40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_token', sa.Column('new_email', postgresql.CITEXT(), nullable=True), schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_token', 'new_email', schema='app')
    # ### end Alembic commands ###
