"""add user is_admin

Revision ID: 3f83224e776f
Revises: ddc2d120576c
Create Date: 2026-06-13 17:51:53.615760+00:00

"""
from alembic import op
import sqlalchemy as sa


revision = '3f83224e776f'
down_revision = 'ddc2d120576c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False), schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin', schema='app')
    # ### end Alembic commands ###
