"""'add llm_call.truncated'

Revision ID: 458ec0c4a35a
Revises: 9d0d376657d5
Create Date: 2026-08-08 19:35:15.847543+00:00

"""
from alembic import op
import sqlalchemy as sa


revision = '458ec0c4a35a'
down_revision = '9d0d376657d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_call', sa.Column('truncated', sa.Boolean(), nullable=True), schema='ingest')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_call', 'truncated', schema='ingest')
    # ### end Alembic commands ###
