"""'add event.provenance'

Revision ID: 49ffb208d5da
Revises: 6fa399bfcd04
Create Date: 2026-08-11 00:27:28.998991+00:00

"""
from alembic import op
import sqlalchemy as sa


revision = '49ffb208d5da'
down_revision = '6fa399bfcd04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('provenance', sa.Text(), server_default=sa.text("'story'"), nullable=False), schema='news')
    op.create_check_constraint('ck_event_provenance', 'event', "provenance IN ('story', 'catalog')", schema='news')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_event_provenance', 'event', schema='news', type_='check')
    op.drop_column('event', 'provenance', schema='news')
    # ### end Alembic commands ###
