"""'add catalog film_alternative_title'

Revision ID: 4a3522ad0785
Revises: 5c8c18b19b86
Create Date: 2026-06-26 17:52:45.538678+00:00

"""
from alembic import op
import sqlalchemy as sa


revision = '4a3522ad0785'
down_revision = '5c8c18b19b86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film_alternative_title',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('film_id', sa.UUID(), nullable=False),
    sa.Column('iso_3166_1', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('title_type', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['catalog.film.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_index('ix_catalog_film_alt_title_film', 'film_alternative_title', ['film_id'], unique=False, schema='catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_catalog_film_alt_title_film', table_name='film_alternative_title', schema='catalog')
    op.drop_table('film_alternative_title', schema='catalog')
    # ### end Alembic commands ###
