"""'add news event and event_story tables'

Revision ID: 4bc1fcd02c53
Revises: 37f37eb3edeb
Create Date: 2026-06-20 14:37:50.970559+00:00

"""
from alembic import op
import sqlalchemy as sa


revision = '4bc1fcd02c53'
down_revision = '37f37eb3edeb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('film_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confidence IN ('confirmed', 'rumored')", name='ck_event_confidence'),
    sa.CheckConstraint("event_type IN ('announced', 'casting', 'production_start', 'production_wrap', 'release_date', 'trailer', 'other')", name='ck_event_type'),
    sa.ForeignKeyConstraint(['film_id'], ['catalog.film.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='news'
    )
    op.create_index('ix_event_film_id', 'event', ['film_id'], unique=False, schema='news')
    op.create_table('event_story',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['news.event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['news.story.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'story_id'),
    sa.UniqueConstraint('story_id', name='uq_event_story_story_id'),
    schema='news'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_story', schema='news')
    op.drop_index('ix_event_film_id', table_name='event', schema='news')
    op.drop_table('event', schema='news')
    # ### end Alembic commands ###
