"""'add run_retrieval_health.soft_breach'

Revision ID: 542c88d0c3f1
Revises: 8a3a615c3c8d
Create Date: 2026-08-12 00:07:26.818511+00:00

"""
from alembic import op
import sqlalchemy as sa


revision = '542c88d0c3f1'
down_revision = '8a3a615c3c8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_retrieval_health', sa.Column('soft_breach', sa.Boolean(), server_default=sa.text('false'), nullable=False), schema='ingest')
    # ### end Alembic commands ###

    # No backfill, and the `false` default is the accurate value rather than a convenience.
    # The soft tier did not exist for these runs, so none of them warned — that is the whole
    # reason saturation went 0% to 7.9% unnoticed and was found by querying prod by hand
    # (NEU-1088 §3.6). Recomputing the flag over history would answer a different question:
    # the threshold is a setting, so a backfill would judge every past run against today's
    # value and read as though the tier had been armed all along.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_retrieval_health', 'soft_breach', schema='ingest')
    # ### end Alembic commands ###
