"""'add film_field_change table and trigger'

Revision ID: 580e5e0d3714
Revises: 91093b92fb54
Create Date: 2026-07-04 15:41:20.269174+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from upmovies.catalog.models import (
    DROP_FILM_FIELD_CHANGE_TRIGGER,
    INSTALL_FILM_FIELD_CHANGE_TRIGGER,
)

revision = '580e5e0d3714'
down_revision = '91093b92fb54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film_field_change',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('film_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.Text(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['catalog.film.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_index('ix_film_field_change_lookup', 'film_field_change', ['film_id', 'field', 'changed_at'], unique=False, schema='catalog')
    # ### end Alembic commands ###

    # asyncpg's extended query protocol rejects multi-statement execute() calls, so
    # each element of the tuple must be run separately (see models.py comment above
    # INSTALL_FILM_FIELD_CHANGE_TRIGGER).
    for stmt in INSTALL_FILM_FIELD_CHANGE_TRIGGER:
        op.execute(stmt)


def downgrade() -> None:
    for stmt in DROP_FILM_FIELD_CHANGE_TRIGGER:
        op.execute(stmt)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_film_field_change_lookup', table_name='film_field_change', schema='catalog')
    op.drop_table('film_field_change', schema='catalog')
    # ### end Alembic commands ###
