"""'add catalog film_release_date'

Revision ID: 5c8c18b19b86
Revises: 6d7e2769ba35
Create Date: 2026-06-26 01:39:11.735874+00:00

"""
from alembic import op
import sqlalchemy as sa


revision = '5c8c18b19b86'
down_revision = '6d7e2769ba35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film_release_date',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('film_id', sa.UUID(), nullable=False),
    sa.Column('iso_3166_1', sa.Text(), nullable=False),
    sa.Column('release_type', sa.Integer(), nullable=False),
    sa.Column('release_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('certification', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('iso_639_1', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['catalog.film.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_index('ix_catalog_film_release_date_film', 'film_release_date', ['film_id'], unique=False, schema='catalog')
    op.create_index('ix_catalog_film_release_date_lookup', 'film_release_date', ['release_date', 'release_type'], unique=False, schema='catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_catalog_film_release_date_lookup', table_name='film_release_date', schema='catalog')
    op.drop_index('ix_catalog_film_release_date_film', table_name='film_release_date', schema='catalog')
    op.drop_table('film_release_date', schema='catalog')
    # ### end Alembic commands ###
