"""'add user.entitled_until'

Revision ID: 6112814b95b5
Revises: 3e6c7bb5536e
Create Date: 2026-09-16 22:47:44.209159+00:00

"""
from alembic import op
import sqlalchemy as sa


revision = '6112814b95b5'
down_revision = '3e6c7bb5536e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('entitled_until', sa.DateTime(timezone=True), nullable=True), schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'entitled_until', schema='app')
    # ### end Alembic commands ###
