"""app.import_candidate and the awaiting_review import status (NEU-1449)

EF-22: an import stops at `awaiting_review` with one candidate per matched film, and no follow is
written until the user confirms the list.

The table is autogenerated and kept as generated. The status half is by hand, because
autogenerate emits neither a changed CHECK nor a changed partial-index predicate:

- `ck_import_job_status` gains `awaiting_review`;
- `uq_import_job_active_per_user` gains it too, so a user holds at most one unconfirmed list —
  the route discards it before opening the next job rather than 409-ing.

**No backfill.** No existing job is waiting on anything: every job that ran before this wrote
its follows directly and ended `succeeded` or `failed`.

The downgrade supersedes any `awaiting_review` job first — `failed` with `error = 'superseded'`,
the same end the route gives one — because the narrower CHECK would otherwise refuse to come
back, and a list nobody can confirm any more is exactly what that status means.

Revision ID: 61b8dca53f8b
Revises: 228c542216fa
Create Date: 2026-09-23 13:29:19.185368+00:00

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "61b8dca53f8b"
down_revision = "228c542216fa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "import_candidate",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("film_id", sa.UUID(), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("headline_release", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("selected", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("skip_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "skip_reason IS NULL OR skip_reason IN ('outside_window')",
            name="ck_import_candidate_skip_reason",
        ),
        sa.CheckConstraint(
            "skip_reason IS NULL OR NOT selected", name="ck_import_candidate_skipped_unselected"
        ),
        sa.ForeignKeyConstraint(["film_id"], ["catalog.film.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["app.import_job.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="app",
    )
    op.create_index(
        "uq_import_candidate_job_film",
        "import_candidate",
        ["job_id", "film_id"],
        unique=True,
        schema="app",
    )

    op.drop_constraint("ck_import_job_status", "import_job", schema="app", type_="check")
    op.create_check_constraint(
        "ck_import_job_status",
        "import_job",
        "status IN ('queued', 'running', 'awaiting_review', 'succeeded', 'failed')",
        schema="app",
    )
    op.drop_index("uq_import_job_active_per_user", table_name="import_job", schema="app")
    op.create_index(
        "uq_import_job_active_per_user",
        "import_job",
        ["user_id"],
        unique=True,
        schema="app",
        postgresql_where=sa.text("status IN ('queued', 'running', 'awaiting_review')"),
    )


def downgrade() -> None:
    op.execute(
        "UPDATE app.import_job SET status = 'failed', error = 'superseded', finished_at = now() "
        "WHERE status = 'awaiting_review'"
    )
    op.drop_index("uq_import_job_active_per_user", table_name="import_job", schema="app")
    op.create_index(
        "uq_import_job_active_per_user",
        "import_job",
        ["user_id"],
        unique=True,
        schema="app",
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.drop_constraint("ck_import_job_status", "import_job", schema="app", type_="check")
    op.create_check_constraint(
        "ck_import_job_status",
        "import_job",
        "status IN ('queued', 'running', 'succeeded', 'failed')",
        schema="app",
    )

    op.drop_index("uq_import_candidate_job_film", table_name="import_candidate", schema="app")
    op.drop_table("import_candidate", schema="app")
