"""'add app.tmdb_auth_request and import_job.tmdb_username'

Revision ID: 63cdebf76f44
Revises: aca8e014fa4e
Create Date: 2026-09-17 20:40:48.115225+00:00

"""
from alembic import op
import sqlalchemy as sa


revision = '63cdebf76f44'
down_revision = 'aca8e014fa4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmdb_auth_request',
    sa.Column('request_token', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_token'),
    schema='app'
    )
    op.create_index('ix_tmdb_auth_request_created_at', 'tmdb_auth_request', ['created_at'], unique=False, schema='app')
    op.add_column('import_job', sa.Column('tmdb_username', sa.Text(), nullable=True), schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_job', 'tmdb_username', schema='app')
    op.drop_index('ix_tmdb_auth_request_created_at', table_name='tmdb_auth_request', schema='app')
    op.drop_table('tmdb_auth_request', schema='app')
    # ### end Alembic commands ###
