"""add person details columns and ingest.credit_hold (NEU-1370)

Revision ID: 63ea0fd6e7dd
Revises: c41f0b7a5d92
Create Date: 2026-09-18 15:34:08.927632+00:00

"""
from alembic import op
import sqlalchemy as sa


revision = '63ea0fd6e7dd'
down_revision = 'c41f0b7a5d92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Sanity holds (ADR-0017, D-8). The three `catalog.person` columns are nullable with no
    # backfill by design: `details_observed_at` doubles as the fetched-ness flag, so every
    # existing row reading NULL is exactly right — nobody has asked TMDB about them, and the
    # sweep asks lazily, one person at a time, only for people a card is about to name.
    op.create_table('credit_hold',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('film_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('credit_type', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('held_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("reason IN ('burst', 'deceased', 'implausible_age')", name='ck_credit_hold_reason'),
    sa.CheckConstraint("release_reason IN ('cleared', 'expired', 'manual')", name='ck_credit_hold_release_reason'),
    sa.CheckConstraint('(released_at IS NULL) = (release_reason IS NULL)', name='ck_credit_hold_released'),
    sa.ForeignKeyConstraint(['film_id'], ['catalog.film.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['catalog.person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('film_id', 'person_id', 'credit_type', 'changed_at', name='uq_credit_hold_change'),
    schema='ingest'
    )
    op.add_column('person', sa.Column('birthday', sa.Date(), nullable=True), schema='catalog')
    op.add_column('person', sa.Column('deathday', sa.Date(), nullable=True), schema='catalog')
    op.add_column('person', sa.Column('details_observed_at', sa.DateTime(timezone=True), nullable=True), schema='catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'details_observed_at', schema='catalog')
    op.drop_column('person', 'deathday', schema='catalog')
    op.drop_column('person', 'birthday', schema='catalog')
    op.drop_table('credit_hold', schema='ingest')
    # ### end Alembic commands ###
