"""'add ingest.run_llm_usage table'

Revision ID: 6d7e2769ba35
Revises: f54c48912dbc
Create Date: 2026-06-24 18:53:26.989724+00:00

"""
from alembic import op
import sqlalchemy as sa


revision = '6d7e2769ba35'
down_revision = 'f54c48912dbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_llm_usage',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('batched', sa.Boolean(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cache_read_input_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cache_creation_input_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.CheckConstraint("stage IN ('link', 'cluster', 'summarize')", name='ck_run_llm_usage_stage'),
    sa.ForeignKeyConstraint(['run_id'], ['ingest.ingest_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'stage', name='uq_run_llm_usage_run_stage'),
    schema='ingest'
    )
    op.create_index(op.f('ix_ingest_run_llm_usage_run_id'), 'run_llm_usage', ['run_id'], unique=False, schema='ingest')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingest_run_llm_usage_run_id'), table_name='run_llm_usage', schema='ingest')
    op.drop_table('run_llm_usage', schema='ingest')
    # ### end Alembic commands ###
