"""'add user_settings and notification'

Revision ID: 6dacd65483eb
Revises: 9c2d41ab7e60
Create Date: 2026-09-18 22:34:40.748353+00:00

"""
from alembic import op
import sqlalchemy as sa


revision = '6dacd65483eb'
down_revision = '9c2d41ab7e60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('digest_cadence', sa.Text(), server_default=sa.text("'weekly'"), nullable=False),
    sa.Column('ical_token', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("digest_cadence IN ('daily', 'weekly', 'off')", name='ck_user_settings_digest_cadence'),
    sa.ForeignKeyConstraint(['user_id'], ['app.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('ical_token'),
    schema='app'
    )
    op.create_table('notification',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("channel IN ('email', 'push')", name='ck_notification_channel'),
    sa.CheckConstraint("kind IN ('alert', 'digest')", name='ck_notification_kind'),
    sa.CheckConstraint("status IN ('queued', 'sent', 'failed', 'suppressed')", name='ck_notification_status'),
    sa.ForeignKeyConstraint(['event_id'], ['news.event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('ix_notification_status_created_at', 'notification', ['status', 'created_at'], unique=False, schema='app')
    op.create_index('uq_notification_user_event_kind_channel', 'notification', ['user_id', 'event_id', 'kind', 'channel'], unique=True, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_notification_user_event_kind_channel', table_name='notification', schema='app')
    op.drop_index('ix_notification_status_created_at', table_name='notification', schema='app')
    op.drop_table('notification', schema='app')
    op.drop_table('user_settings', schema='app')
    # ### end Alembic commands ###
