"""'add news.event_summary table'

Revision ID: 72cefc645fdc
Revises: 4bc1fcd02c53
Create Date: 2026-06-22 22:00:28.473244+00:00

"""
from alembic import op
import sqlalchemy as sa


revision = '72cefc645fdc'
down_revision = '4bc1fcd02c53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_summary',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['news.event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id'),
    schema='news'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_summary', schema='news')
    # ### end Alembic commands ###
