"""'add watch provider tables and providers ingest kind'

Revision ID: 7a45131257b9
Revises: f2703d3804bd
Create Date: 2026-09-18 19:59:38.510563+00:00

"""
from alembic import op
import sqlalchemy as sa


revision = '7a45131257b9'
down_revision = 'f2703d3804bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watch_provider',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('logo_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_table('availability_first_seen',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('film_id', sa.UUID(), nullable=False),
    sa.Column('region', sa.Text(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('monetization_type', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("monetization_type IN ('flatrate', 'rent', 'buy')", name='ck_availability_first_seen_monetization_type'),
    sa.ForeignKeyConstraint(['film_id'], ['catalog.film.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['catalog.watch_provider.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('film_id', 'region', 'provider_id', 'monetization_type', name='uq_availability_first_seen'),
    schema='catalog'
    )
    op.create_index('ix_catalog_availability_first_seen_film', 'availability_first_seen', ['film_id'], unique=False, schema='catalog')
    op.create_table('film_availability_current',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('film_id', sa.UUID(), nullable=False),
    sa.Column('region', sa.Text(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('monetization_type', sa.Text(), nullable=False),
    sa.Column('link', sa.Text(), nullable=True),
    sa.CheckConstraint("monetization_type IN ('flatrate', 'rent', 'buy')", name='ck_film_availability_current_monetization_type'),
    sa.ForeignKeyConstraint(['film_id'], ['catalog.film.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['catalog.watch_provider.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('film_id', 'region', 'provider_id', 'monetization_type', name='uq_film_availability_current'),
    schema='catalog'
    )
    op.create_index('ix_catalog_film_availability_current_film', 'film_availability_current', ['film_id'], unique=False, schema='catalog')
    # ### end Alembic commands ###
    # By hand: autogenerate never diffs CheckConstraints (AGENTS.md). The provider poll opens
    # runs of its own kind, so the constraint has to admit it before the first one is written.
    op.drop_constraint("ck_ingest_run_kind", "ingest_run", type_="check", schema="ingest")
    op.create_check_constraint(
        "ck_ingest_run_kind",
        "ingest_run",
        "kind IN ('tmdb', 'feeds', 'link', 'synthesize', 'sweep', 'providers')",
        schema="ingest",
    )


def downgrade() -> None:
    op.drop_constraint("ck_ingest_run_kind", "ingest_run", type_="check", schema="ingest")
    op.create_check_constraint(
        "ck_ingest_run_kind",
        "ingest_run",
        "kind IN ('tmdb', 'feeds', 'link', 'synthesize', 'sweep')",
        schema="ingest",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_catalog_film_availability_current_film', table_name='film_availability_current', schema='catalog')
    op.drop_table('film_availability_current', schema='catalog')
    op.drop_index('ix_catalog_availability_first_seen_film', table_name='availability_first_seen', schema='catalog')
    op.drop_table('availability_first_seen', schema='catalog')
    op.drop_table('watch_provider', schema='catalog')
    # ### end Alembic commands ###
