"""'add news.story_person and news.resolution_cache (NEU-1360)'

Revision ID: 8013f01a60ab
Revises: 63cdebf76f44
Create Date: 2026-09-17 21:55:26.352516+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '8013f01a60ab'
down_revision = '63cdebf76f44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resolution_cache',
    sa.Column('source_domain', sa.Text(), nullable=False),
    sa.Column('name_as_written', sa.Text(), nullable=False),
    sa.Column('film_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['catalog.film.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['catalog.person.id'], name='fk_resolution_cache_person', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('source_domain', 'name_as_written', 'film_id'),
    schema='news'
    )
    op.create_table('story_person',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('name_as_written', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('evidence_span', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("path IS NULL OR path IN ('accepted', 'tiebreak', 'unlinked', 'not_in_tmdb')", name='ck_story_person_path'),
    sa.ForeignKeyConstraint(['person_id'], ['catalog.person.id'], name='fk_story_person_person', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['news.story.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='news'
    )
    op.create_index('ix_story_person_person_id', 'story_person', ['person_id'], unique=False, schema='news')
    op.create_index('ix_story_person_story_id', 'story_person', ['story_id'], unique=False, schema='news')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_story_person_story_id', table_name='story_person', schema='news')
    op.drop_index('ix_story_person_person_id', table_name='story_person', schema='news')
    op.drop_table('story_person', schema='news')
    op.drop_table('resolution_cache', schema='news')
    # ### end Alembic commands ###
