"""'add film tmdb_missing_at tombstone'

Revision ID: 8a3a615c3c8d
Revises: 8ec483514987
Create Date: 2026-08-11 21:24:46.771502+00:00

"""
from alembic import op
import sqlalchemy as sa

from upmovies.catalog.models import INSTALL_FILM_FIELD_CHANGE_TRIGGER


revision = '8a3a615c3c8d'
down_revision = '8ec483514987'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('tmdb_missing_at', sa.DateTime(timezone=True), nullable=True), schema='catalog')
    op.add_column('person', sa.Column('tmdb_missing_at', sa.DateTime(timezone=True), nullable=True), schema='catalog')
    # ### end Alembic commands ###

    # `tmdb_missing_at` joins FILM_FIELD_CHANGE_DENYLIST, so the trigger function has to be
    # replaced to pick it up — exactly as `release_dates_observed_at` did in 8ec483514987 and
    # `credits_observed_at` in 957421e2651e. Without it, tombstoning a deleted film lands a
    # `film_field_change` row, which `field_events` would then card as a public event
    # announcing that TMDB deleted a record — news about our source, not about the production
    # — and which would also revive the film in `dormant_film_clause`. CREATE OR REPLACE, so
    # reinstalling is idempotent; one op.execute per statement because asyncpg's extended
    # query protocol rejects multi-statement calls (see the note in models.py).
    for stmt in INSTALL_FILM_FIELD_CHANGE_TRIGGER:
        op.execute(stmt)

    # No backfill. Every existing film and person starts `tmdb_missing_at IS NULL`, so the
    # first sweep after this ships re-derives the tombstones from TMDB itself — one 404 each
    # for the ~12 film ids currently wedging the refresh set and the ~50 dead person ids, and
    # then once per `SWEEP_DORMANT_REFRESH_DAYS` for films, never again for people until a
    # credit names them (NEU-1124).
    #
    # `person.tmdb_missing_at` needs no trigger work: the field-change trigger is installed on
    # `catalog.film` only.


def downgrade() -> None:
    # The trigger function is deliberately left as installed above: its denylist entry for a
    # column that no longer exists is inert, and rebuilding the previous function body here
    # would fork the one place that SQL is written.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'tmdb_missing_at', schema='catalog')
    op.drop_column('film', 'tmdb_missing_at', schema='catalog')
    # ### end Alembic commands ###
