"""add event_summary edited_at edited_by

Revision ID: 8db18de6d77c
Revises: 1b46a53537db
Create Date: 2026-07-06 14:01:46.974538+00:00

"""
from alembic import op
import sqlalchemy as sa


revision = '8db18de6d77c'
down_revision = '1b46a53537db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_summary', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True), schema='news')
    op.add_column('event_summary', sa.Column('edited_by', sa.UUID(), nullable=True), schema='news')
    op.create_foreign_key('fk_event_summary_edited_by_user', 'event_summary', 'user', ['edited_by'], ['id'], source_schema='news', referent_schema='app', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_event_summary_edited_by_user', 'event_summary', schema='news', type_='foreignkey')
    op.drop_column('event_summary', 'edited_by', schema='news')
    op.drop_column('event_summary', 'edited_at', schema='news')
    # ### end Alembic commands ###
