"""'add film_release_date_change and release_dates_observed_at'

Revision ID: 8ec483514987
Revises: b7c31d9a4e02
Create Date: 2026-08-11 16:12:07.610492+00:00

"""
from alembic import op
import sqlalchemy as sa

from upmovies.catalog.models import INSTALL_FILM_FIELD_CHANGE_TRIGGER


revision = '8ec483514987'
down_revision = 'b7c31d9a4e02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film_release_date_change',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('film_id', sa.UUID(), nullable=False),
    sa.Column('iso_3166_1', sa.Text(), nullable=False),
    sa.Column('release_type', sa.Integer(), nullable=False),
    sa.Column('previous_date', sa.Date(), nullable=True),
    sa.Column('new_date', sa.Date(), nullable=False),
    sa.Column('change', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['catalog.film.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_index('ix_catalog_film_release_date_change_lookup', 'film_release_date_change', ['film_id', 'changed_at'], unique=False, schema='catalog')
    op.add_column('film', sa.Column('release_dates_observed_at', sa.DateTime(timezone=True), nullable=True), schema='catalog')
    # ### end Alembic commands ###

    # `release_dates_observed_at` joins FILM_FIELD_CHANGE_DENYLIST, so the trigger function has
    # to be replaced to pick it up — exactly as `credits_observed_at` did in 957421e2651e.
    # Without it the marker's own write lands a `film_field_change` row on the first refresh of
    # every film, which both floods that table and makes every film look active to
    # `dormant_film_clause` — dormancy would stop governing anything. CREATE OR REPLACE, so
    # reinstalling is idempotent; one op.execute per statement because asyncpg's extended query
    # protocol rejects multi-statement calls (see the note in models.py).
    for stmt in INSTALL_FILM_FIELD_CHANGE_TRIGGER:
        op.execute(stmt)

    # No backfill, deliberately. Every existing film keeps `release_dates_observed_at IS NULL`,
    # so its next refresh records the slate as a *baseline* and cards nothing — which is what
    # stops the whole catalog carding its entire release list the first time this ships
    # (spec §5.3). Events begin from the observation after that.


def downgrade() -> None:
    # The trigger function is deliberately left as installed above: its denylist entry for a
    # column that no longer exists is inert, and rebuilding the previous function body here
    # would fork the one place that SQL is written.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('film', 'release_dates_observed_at', schema='catalog')
    op.drop_index('ix_catalog_film_release_date_change_lookup', table_name='film_release_date_change', schema='catalog')
    op.drop_table('film_release_date_change', schema='catalog')
    # ### end Alembic commands ###
