"""'add catalog.film_credit_change and film.credits_observed_at'

Revision ID: 957421e2651e
Revises: 1624d2f7f412
Create Date: 2026-08-11 01:30:34.688023+00:00

"""
from alembic import op
import sqlalchemy as sa

from upmovies.catalog.models import INSTALL_FILM_FIELD_CHANGE_TRIGGER


revision = '957421e2651e'
down_revision = '1624d2f7f412'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film_credit_change',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('film_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('credit_type', sa.Text(), nullable=False),
    sa.Column('job', sa.Text(), nullable=True),
    sa.Column('change', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['catalog.film.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['catalog.person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_index('ix_catalog_film_credit_change_lookup', 'film_credit_change', ['film_id', 'changed_at'], unique=False, schema='catalog')
    op.add_column('film', sa.Column('credits_observed_at', sa.DateTime(timezone=True), nullable=True), schema='catalog')
    # ### end Alembic commands ###

    # `credits_observed_at` joins FILM_FIELD_CHANGE_DENYLIST, so the trigger function has to
    # be replaced to pick it up — otherwise setting the marker on admission writes a history
    # row that makes the film look active to `dormant_film_clause`. CREATE OR REPLACE, so
    # reinstalling is idempotent; one op.execute per statement because asyncpg's extended
    # query protocol rejects multi-statement calls (see the note in models.py).
    for stmt in INSTALL_FILM_FIELD_CHANGE_TRIGGER:
        op.execute(stmt)


def downgrade() -> None:
    # The trigger function is deliberately left as installed above: its denylist entry for a
    # column that no longer exists is inert, and rebuilding the previous function body here
    # would fork the one place that SQL is written.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('film', 'credits_observed_at', schema='catalog')
    op.drop_index('ix_catalog_film_credit_change_lookup', table_name='film_credit_change', schema='catalog')
    op.drop_table('film_credit_change', schema='catalog')
    # ### end Alembic commands ###
