"""add film_video and videos_observed_at

Revision ID: 97f1fd284a2d
Revises: f573fdbab45e
Create Date: 2026-09-19 19:10:57.940614+00:00

"""
from alembic import op
import sqlalchemy as sa

from upmovies.catalog.models import INSTALL_FILM_FIELD_CHANGE_TRIGGER


revision = '97f1fd284a2d'
down_revision = 'f573fdbab45e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film_video',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('film_id', sa.UUID(), nullable=False),
    sa.Column('site', sa.Text(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['catalog.film.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('film_id', 'site', 'key', name='uq_film_video'),
    schema='catalog'
    )
    op.create_index('ix_catalog_film_video_film', 'film_video', ['film_id'], unique=False, schema='catalog')
    op.add_column('film', sa.Column('videos_observed_at', sa.DateTime(timezone=True), nullable=True), schema='catalog')
    # ### end Alembic commands ###

    # `videos_observed_at` joins FILM_FIELD_CHANGE_DENYLIST, so the trigger function has to be
    # replaced to pick it up — exactly as `tmdb_missing_at` did in 8a3a615c3c8d and
    # `release_dates_observed_at` in 8ec483514987. Without it, every film's baseline video poll
    # lands a `film_field_change` row, which `field_events` would card as a public event
    # announcing that we looked at a film — and which would revive the film in
    # `dormant_film_clause` on the day it was polled. CREATE OR REPLACE, so reinstalling is
    # idempotent; one op.execute per statement because asyncpg's extended query protocol
    # rejects multi-statement calls (see the note in models.py).
    for stmt in INSTALL_FILM_FIELD_CHANGE_TRIGGER:
        op.execute(stmt)

    # No backfill, and deliberately so: every film starts `videos_observed_at IS NULL`, which
    # is exactly right. The first poll after this ships is each film's baseline — it records
    # whatever TMDB already holds and cards nothing (ADR-0014), so a catalogue admitted with
    # years of trailers behind it stays silent instead of emptying itself onto the feed.


def downgrade() -> None:
    # The trigger function is deliberately left as installed above, on 8a3a615c3c8d's terms:
    # a denylist entry for a column that no longer exists is inert, and rebuilding the previous
    # body here would fork the one place that SQL is written.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('film', 'videos_observed_at', schema='catalog')
    op.drop_index('ix_catalog_film_video_film', table_name='film_video', schema='catalog')
    op.drop_table('film_video', schema='catalog')
    # ### end Alembic commands ###
