"""'add ingest.link_retrieval_probe and ingest.run_retrieval_health'

Revision ID: 9d0d376657d5
Revises: ddeba5194a23
Create Date: 2026-08-07 18:54:13.398297+00:00

"""
from alembic import op
import sqlalchemy as sa


revision = '9d0d376657d5'
down_revision = 'ddeba5194a23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_retrieval_health',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('stories_retrieved', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('zero_candidate_stories', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('saturated_stories', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('mean_candidates', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(stories_retrieved = 0) = (mean_candidates IS NULL)', name='ck_run_retrieval_health_mean'),
    sa.CheckConstraint('saturated_stories BETWEEN 0 AND stories_retrieved', name='ck_run_retrieval_health_saturated'),
    sa.CheckConstraint('stories_retrieved >= 0', name='ck_run_retrieval_health_denominator'),
    sa.CheckConstraint('zero_candidate_stories BETWEEN 0 AND stories_retrieved', name='ck_run_retrieval_health_zero_candidate'),
    sa.ForeignKeyConstraint(['run_id'], ['ingest.ingest_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', name='uq_run_retrieval_health_run'),
    schema='ingest'
    )
    op.create_table('link_retrieval_probe',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('film_id', sa.UUID(), nullable=False),
    sa.Column('retrieved', sa.Boolean(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('candidate_count >= 0', name='ck_link_retrieval_probe_candidate_count'),
    sa.CheckConstraint('rank IS NULL OR rank <= candidate_count', name='ck_link_retrieval_probe_rank_in_set'),
    sa.CheckConstraint('rank IS NULL OR rank >= 1', name='ck_link_retrieval_probe_rank_positive'),
    sa.CheckConstraint('rank IS NULL OR score IS NOT NULL', name='ck_link_retrieval_probe_ranked_has_score'),
    sa.CheckConstraint('retrieved = (rank IS NOT NULL)', name='ck_link_retrieval_probe_retrieved'),
    sa.CheckConstraint('score IS NULL OR (score >= 0 AND score <= 1)', name='ck_link_retrieval_probe_score'),
    sa.ForeignKeyConstraint(['film_id'], ['catalog.film.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['ingest.ingest_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['news.story.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'story_id', name='uq_link_retrieval_probe_run_story'),
    schema='ingest'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link_retrieval_probe', schema='ingest')
    op.drop_table('run_retrieval_health', schema='ingest')
    # ### end Alembic commands ###
