"""'follows are binary: drop coverage, delete imported person follows'

M2 (NEU-1432, EF-1): a follow has no tiers. `app.follow.coverage` and its CHECK go, and with
them the `lead | major | any` control NEU-1418 shipped two days ago.

**The delete is the half that is not schema.** Every person follow whose `source` is
`letterboxd_import` or `tmdb_import` is removed. Those rows were written by the ratings and
favorites path (D-15, D-16) as an *inference* — the user rated a film, so we followed its
lead actors — and the narrow default coverage is the only reason that was ever tolerable.
Under EF-2 each one would push on every credit change of everyone the user once gave four
stars to, which is not a thing anybody asked for. EF-20 deletes the path that writes them;
this deletes what it already wrote.

**Title follows and manual follows are kept**, imported or not: a title follow is a film the
user put on a list, which is a choice, and `source` records where the choice was made rather
than casting doubt on it.

**Hand-written, not autogenerated.** Autogenerate does emit the `DROP COLUMN`, but not the
`DELETE`, and the two have to land in one revision: a coverage-less table with the imported
rows still on it is exactly the state EF-1 is not willing to be in for a deploy.

**The downgrade restores the schema and says what it cannot restore.** The column comes back
NOT NULL at `lead`, which is what every surviving row would have read at anyway — a row at
`major` or `any` loses the tier it was set to. The deleted follows do not come back at all;
re-running the import is the only way, and that is EF-22's job now.

Revision ID: a5e1c93b7d40
Revises: c7a1e4d9b2f3
Create Date: 2026-09-21 18:40:00.000000+00:00

"""
import sqlalchemy as sa
from alembic import op

revision = 'a5e1c93b7d40'
down_revision = 'c7a1e4d9b2f3'
branch_labels = None
depends_on = None

_IMPORT_SOURCES = "('letterboxd_import', 'tmdb_import')"


def upgrade() -> None:
    # 1. The inferred follows, before the column they were tolerable under goes. Order is not
    # load-bearing here — the predicate reads `entity_type` and `source`, never `coverage` —
    # but reading the delete first is how the revision reads as one decision.
    op.execute(
        "DELETE FROM app.follow "
        f"WHERE entity_type = 'person' AND source IN {_IMPORT_SOURCES}"
    )
    # 2. The CHECK by name, so the parity test's name comparison has nothing left to find.
    # Postgres would drop it with the column anyway; naming it is what documents that.
    op.drop_constraint('ck_follow_coverage', 'follow', schema='app')
    op.drop_column('follow', 'coverage', schema='app')


def downgrade() -> None:
    op.add_column(
        'follow',
        sa.Column('coverage', sa.Text(), nullable=False, server_default='lead'),
        schema='app',
    )
    op.create_check_constraint(
        'ck_follow_coverage', 'follow', "coverage IN ('lead', 'major', 'any')", schema='app'
    )
