"""'add app.import_job for library imports (NEU-1356)'

Revision ID: aca8e014fa4e
Revises: f758b863d67b
Create Date: 2026-09-17 18:56:57.112550+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'aca8e014fa4e'
down_revision = 'f758b863d67b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_job',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('rows_total', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('rows_done', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('watchlist_created', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('follows_created', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('unmatched', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("source IN ('letterboxd', 'tmdb')", name='ck_import_job_source'),
    sa.CheckConstraint("status IN ('queued', 'running', 'succeeded', 'failed')", name='ck_import_job_status'),
    sa.ForeignKeyConstraint(['user_id'], ['app.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('ix_import_job_user_id_created_at', 'import_job', ['user_id', 'created_at'], unique=False, schema='app')
    op.create_index('uq_import_job_active_per_user', 'import_job', ['user_id'], unique=True, schema='app', postgresql_where=sa.text("status IN ('queued', 'running')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_import_job_active_per_user', table_name='import_job', schema='app', postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.drop_index('ix_import_job_user_id_created_at', table_name='import_job', schema='app')
    op.drop_table('import_job', schema='app')
    # ### end Alembic commands ###
