"""'add source_domain table'

Revision ID: b0b9de2b93a2
Revises: 46406c2cc268
Create Date: 2026-07-01 19:20:40.247997+00:00

"""
from alembic import op
import sqlalchemy as sa


revision = 'b0b9de2b93a2'
down_revision = '46406c2cc268'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_domain',
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('llm_tier', sa.Text(), nullable=True),
    sa.Column('llm_reason', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.Text(), nullable=True),
    sa.Column('admin_override', sa.Text(), server_default=sa.text("'none'"), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('judged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("admin_override IN ('none', 'block', 'allow', 'trust')", name='ck_source_domain_override'),
    sa.CheckConstraint("llm_tier IS NULL OR llm_tier IN ('trusted', 'acceptable', 'low')", name='ck_source_domain_tier'),
    sa.PrimaryKeyConstraint('domain'),
    schema='news'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_domain', schema='news')
    # ### end Alembic commands ###
