"""add collection_attached and collection_removed event types

Revision ID: b7c1a9e40d32
Revises: 1cdd4fe77a5e
Create Date: 2026-09-21 12:00:00.000000+00:00

The franchise half of EF-5 (NEU-1434). Only the event vocabulary moves: unlike the studio
half this needs no history table and no bookkeeping column, because `film.collection_id` is a
plain `catalog.film` column outside `FILM_FIELD_CHANGE_DENYLIST` and `catalog.film_field_change`
has been recording its changes since the trigger shipped.

Hand-written rather than autogenerated: Alembic's autogenerate does not emit a change to an
existing table's `CheckConstraint`, and `ck_event_type` is compared by name *and* definition by
`tests/integration/test_migrations.py`, so the SQL here has to match `news.models.Event`'s
`__table_args__` exactly.
"""

from alembic import op

revision = "b7c1a9e40d32"
down_revision = "1cdd4fe77a5e"
branch_labels = None
depends_on = None

_NEW = (
    "'announced', 'casting', 'collection_attached', 'collection_removed', "
    "'company_attached', 'company_removed', 'credit_removed', 'crew_attached', "
    "'now_available', 'production_start', 'production_wrap', 'release_date', "
    "'trailer', 'first_look', 'other'"
)
_OLD = (
    "'announced', 'casting', 'company_attached', 'company_removed', "
    "'credit_removed', 'crew_attached', "
    "'now_available', 'production_start', 'production_wrap', 'release_date', "
    "'trailer', 'first_look', 'other'"
)


def upgrade() -> None:
    op.execute("ALTER TABLE news.event DROP CONSTRAINT ck_event_type")
    op.execute(f"ALTER TABLE news.event ADD CONSTRAINT ck_event_type CHECK (event_type IN ({_NEW}))")


def downgrade() -> None:
    # A franchise card cannot satisfy the old constraint, so the events the phase carded go
    # with the type — there is nothing else they could be. Their summaries follow on the
    # `event_summary` FK cascade. The `film_field_change` rows they were read from are
    # untouched and would be re-carded if the type ever came back, since nothing stamps them.
    op.execute(
        "DELETE FROM news.event "
        "WHERE event_type IN ('collection_attached', 'collection_removed')"
    )
    op.execute("ALTER TABLE news.event DROP CONSTRAINT ck_event_type")
    op.execute(f"ALTER TABLE news.event ADD CONSTRAINT ck_event_type CHECK (event_type IN ({_OLD}))")
