"""'add user.email_verified_at and app.email_token'

Revision ID: c206c3092a40
Revises: c42516096572
Create Date: 2026-09-15 22:41:10.738217+00:00

"""
from alembic import op
import sqlalchemy as sa


revision = 'c206c3092a40'
down_revision = 'c42516096572'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_token',
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token'),
    schema='app'
    )
    op.create_index('ix_email_token_user_id_purpose', 'email_token', ['user_id', 'purpose'], unique=False, schema='app')
    op.add_column('user', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True), schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_verified_at', schema='app')
    op.drop_index('ix_email_token_user_id_purpose', table_name='email_token', schema='app')
    op.drop_table('email_token', schema='app')
    # ### end Alembic commands ###
