"""'follow coverage: rename all -> major, add the any tier'

M9 (NEU-1418, D-48): the person-follow tiers become `lead | major | any`. `all` is renamed
because a tier called "all" beside one that reaches more is the vocabulary drift `CONTEXT.md`
exists to stop; `any` is the new widest tier, reaching every credit a person holds.

**Hand-written, not autogenerated.** Alembic does emit table CHECK changes for an existing
table, but only as an `op.create_check_constraint` beside a `drop_constraint` it cannot order
against the UPDATE that has to run between them — the rename must land *before* the new CHECK
is issued, or every `all` row violates it. So the three steps are spelled here in order.

**The downgrade refuses rather than guesses.** `major` maps back to `all` cleanly, but an `any`
row has no pre-NEU-1416 spelling at all: narrowing it to `major` would silently take away
coverage the user asked for, and widening does not exist. A downgrade with `any` rows on the
table raises and tells the operator to narrow them first.

Revision ID: c7a1e4d9b2f3
Revises: 0a2426602d7c
Create Date: 2026-09-20 21:10:00.000000+00:00

"""
from alembic import op

revision = 'c7a1e4d9b2f3'
down_revision = '0a2426602d7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 1. Drop the old CHECK first: it names `all`, which step 2 is about to remove.
    op.drop_constraint('ck_follow_coverage', 'follow', schema='app')
    # 2. The rename. Rows at `all` shipped the same day (NEU-1414), so this is a one-line
    # data migration rather than a backfill.
    op.execute("UPDATE app.follow SET coverage = 'major' WHERE coverage = 'all'")
    # 3. Re-issue it over the three tiers. Same name as before, because the parity test
    # compares constraint names against the model's `ck_follow_coverage`.
    op.create_check_constraint(
        'ck_follow_coverage', 'follow', "coverage IN ('lead', 'major', 'any')", schema='app'
    )


def downgrade() -> None:
    widest = op.get_bind().exec_driver_sql(
        "SELECT count(*) FROM app.follow WHERE coverage = 'any'"
    ).scalar()
    if widest:
        raise RuntimeError(
            f"{widest} follow(s) are at coverage 'any', which has no spelling before "
            "NEU-1416. Narrow them to 'major' (or delete them) before downgrading; "
            "this migration will not choose for the user."
        )
    op.drop_constraint('ck_follow_coverage', 'follow', schema='app')
    op.execute("UPDATE app.follow SET coverage = 'all' WHERE coverage = 'major'")
    op.create_check_constraint(
        'ck_follow_coverage', 'follow', "coverage IN ('lead', 'all')", schema='app'
    )
