"""'add event.region'

Revision ID: c8968b592f4c
Revises: d1b0671be1d5
Create Date: 2026-06-30 22:57:16.513691+00:00

"""
from alembic import op
import sqlalchemy as sa


revision = 'c8968b592f4c'
down_revision = 'd1b0671be1d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('region', sa.Text(), nullable=True), schema='news')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'region', schema='news')
    # ### end Alembic commands ###
