"""add the canceled event type

Revision ID: d3f5a81c6b47
Revises: b7c1a9e40d32
Create Date: 2026-09-22 12:00:00.000000+00:00

EF-6 (NEU-1435). Only the event vocabulary moves: a cancellation is read from the
`catalog.film_field_change` rows the trigger has always recorded for `film.status`, so there is
no history table, no bookkeeping column and no backfill — the same shape as the franchise half.

Hand-written rather than autogenerated: Alembic's autogenerate does not emit a change to an
existing table's `CheckConstraint`, and `ck_event_type` is compared by name *and* definition by
`tests/integration/test_migrations.py`, so the SQL here has to match `news.models.Event`'s
`__table_args__` exactly.
"""

from alembic import op

revision = "d3f5a81c6b47"
down_revision = "b7c1a9e40d32"
branch_labels = None
depends_on = None

_NEW = (
    "'announced', 'canceled', 'casting', 'collection_attached', 'collection_removed', "
    "'company_attached', 'company_removed', 'credit_removed', 'crew_attached', "
    "'now_available', 'production_start', 'production_wrap', 'release_date', "
    "'trailer', 'first_look', 'other'"
)
_OLD = (
    "'announced', 'casting', 'collection_attached', 'collection_removed', "
    "'company_attached', 'company_removed', 'credit_removed', 'crew_attached', "
    "'now_available', 'production_start', 'production_wrap', 'release_date', "
    "'trailer', 'first_look', 'other'"
)


def upgrade() -> None:
    op.execute("ALTER TABLE news.event DROP CONSTRAINT ck_event_type")
    op.execute(f"ALTER TABLE news.event ADD CONSTRAINT ck_event_type CHECK (event_type IN ({_NEW}))")


def downgrade() -> None:
    # A cancellation card cannot satisfy the old constraint, so the events the phase carded go
    # with the type — there is nothing else they could be. Their summaries follow on the
    # `event_summary` FK cascade. The `film_field_change` rows they were read from are untouched
    # and would be re-carded if the type ever came back, since nothing stamps them.
    op.execute("DELETE FROM news.event WHERE event_type = 'canceled'")
    op.execute("ALTER TABLE news.event DROP CONSTRAINT ck_event_type")
    op.execute(f"ALTER TABLE news.event ADD CONSTRAINT ck_event_type CHECK (event_type IN ({_OLD}))")
