"""'add ingest schema and ingest_run'

Revision ID: ddc2d120576c
Revises: ea7cc4565f29
Create Date: 2026-06-06 22:58:28.493403+00:00

"""
from alembic import op
import sqlalchemy as sa


revision = 'ddc2d120576c'
down_revision = 'ea7cc4565f29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_run',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_processed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('items_failed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_progress_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("kind IN ('tmdb', 'feeds')", name='ck_ingest_run_kind'),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'failed', 'cancelled')", name='ck_ingest_run_status'),
    sa.PrimaryKeyConstraint('id'),
    schema='ingest'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingest_run', schema='ingest')
    # ### end Alembic commands ###
