"""'add ingest.llm_call'

Revision ID: ddeba5194a23
Revises: 8db18de6d77c
Create Date: 2026-08-06 16:28:22.827620+00:00

"""
from alembic import op
import sqlalchemy as sa


revision = 'ddeba5194a23'
down_revision = '8db18de6d77c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_call',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cache_read_input_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cache_creation_input_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error_type', sa.Text(), nullable=True),
    sa.Column('parse_ok', sa.Boolean(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("stage IN ('link', 'cluster', 'summarize', 'source_judge')", name='ck_llm_call_stage'),
    sa.CheckConstraint('attempts >= 1', name='ck_llm_call_attempts'),
    sa.ForeignKeyConstraint(['run_id'], ['ingest.ingest_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ingest'
    )
    op.create_index(op.f('ix_ingest_llm_call_run_id'), 'llm_call', ['run_id'], unique=False, schema='ingest')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingest_llm_call_run_id'), table_name='llm_call', schema='ingest')
    op.drop_table('llm_call', schema='ingest')
    # ### end Alembic commands ###
