"""'add person and film_credit tables'

Revision ID: e07c50f357d7
Revises: 4a3522ad0785
Create Date: 2026-06-26 19:20:54.715844+00:00

"""
from alembic import op
import sqlalchemy as sa


revision = 'e07c50f357d7'
down_revision = '4a3522ad0785'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=True),
    sa.Column('profile_path', sa.Text(), nullable=True),
    sa.Column('known_for_department', sa.Text(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_table('film_credit',
    sa.Column('credit_id', sa.Text(), nullable=False),
    sa.Column('film_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('credit_type', sa.Text(), nullable=False),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('job', sa.Text(), nullable=True),
    sa.Column('character', sa.Text(), nullable=True),
    sa.Column('credit_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['catalog.film.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['catalog.person.id'], ),
    sa.PrimaryKeyConstraint('credit_id'),
    schema='catalog'
    )
    op.create_index('ix_catalog_film_credit_film', 'film_credit', ['film_id'], unique=False, schema='catalog')
    op.create_index('ix_catalog_film_credit_person', 'film_credit', ['person_id'], unique=False, schema='catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_catalog_film_credit_person', table_name='film_credit', schema='catalog')
    op.drop_index('ix_catalog_film_credit_film', table_name='film_credit', schema='catalog')
    op.drop_table('film_credit', schema='catalog')
    op.drop_table('person', schema='catalog')
    # ### end Alembic commands ###
