"""'initial app catalog news schema'

Revision ID: ea7cc4565f29
Revises: 
Create Date: 2026-06-06 21:02:15.879102+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'ea7cc4565f29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempt',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('ix_login_attempt_email_at', 'login_attempt', ['email', 'attempted_at'], unique=False, schema='app')
    op.create_table('user',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='app'
    )
    op.create_table('film',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('imdb_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('original_title', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tmdb_id'),
    schema='catalog'
    )
    op.create_table('invite',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('email_hint', postgresql.CITEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['consumed_by_user_id'], ['app.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('code'),
    schema='app'
    )
    op.create_table('session',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('ix_session_expires_at', 'session', ['expires_at'], unique=False, schema='app')
    op.create_index('ix_session_user_id', 'session', ['user_id'], unique=False, schema='app')
    op.create_table('story',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('film_id', sa.UUID(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['catalog.film.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url'),
    schema='news'
    )
    op.create_index('ix_story_film_id', 'story', ['film_id'], unique=False, schema='news')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_story_film_id', table_name='story', schema='news')
    op.drop_table('story', schema='news')
    op.drop_index('ix_session_user_id', table_name='session', schema='app')
    op.drop_index('ix_session_expires_at', table_name='session', schema='app')
    op.drop_table('session', schema='app')
    op.drop_table('invite', schema='app')
    op.drop_table('film', schema='catalog')
    op.drop_table('user', schema='app')
    op.drop_index('ix_login_attempt_email_at', table_name='login_attempt', schema='app')
    op.drop_table('login_attempt', schema='app')
    # ### end Alembic commands ###
