"""'add follow, watchlist_item and watchlist_dismissal'

Revision ID: f758b863d67b
Revises: 65ba376f1b57
Create Date: 2026-09-17 03:16:50.717398+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'f758b863d67b'
down_revision = '65ba376f1b57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entity_type IN ('person', 'company', 'franchise', 'title')", name='ck_follow_entity_type'),
    sa.CheckConstraint("source IN ('manual', 'letterboxd_import', 'tmdb_import', 'derived')", name='ck_follow_source'),
    sa.ForeignKeyConstraint(['user_id'], ['app.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'entity_type', 'entity_id'),
    schema='app'
    )
    op.create_index('ix_follow_entity', 'follow', ['entity_type', 'entity_id'], unique=False, schema='app')
    op.create_table('watchlist_dismissal',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('film_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['catalog.film.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'film_id'),
    schema='app'
    )
    op.create_table('watchlist_item',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('film_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('alert_prefs', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{stream}'::text[]"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("alert_prefs <@ ARRAY['buy', 'rent', 'stream']::text[]", name='ck_watchlist_item_alert_prefs'),
    sa.CheckConstraint("source IN ('manual', 'derived_from_follow', 'letterboxd_import', 'tmdb_import')", name='ck_watchlist_item_source'),
    sa.ForeignKeyConstraint(['film_id'], ['catalog.film.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'film_id'),
    schema='app'
    )
    op.create_index('ix_watchlist_item_film_id', 'watchlist_item', ['film_id'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_watchlist_item_film_id', table_name='watchlist_item', schema='app')
    op.drop_table('watchlist_item', schema='app')
    op.drop_table('watchlist_dismissal', schema='app')
    op.drop_index('ix_follow_entity', table_name='follow', schema='app')
    op.drop_table('follow', schema='app')
    # ### end Alembic commands ###
