"""add push_subscription (NEU-1387)

Revision ID: f798756f89c7
Revises: 97f1fd284a2d
Create Date: 2026-09-19 20:37:52.672846+00:00

"""
from alembic import op
import sqlalchemy as sa


revision = 'f798756f89c7'
down_revision = '97f1fd284a2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscription',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint'),
    schema='app'
    )
    op.create_index('ix_push_subscription_user_id', 'push_subscription', ['user_id'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_push_subscription_user_id', table_name='push_subscription', schema='app')
    op.drop_table('push_subscription', schema='app')
    # ### end Alembic commands ###
